// The todocli contract this panel is written against (PLAN §3.5, §3.7;
// appendix A5): tests/fixtures/contract/ holds what the real binary prints,
// generated by todocli's tests/contract.rs and vendored here byte for byte,
// pinned by SHA-256 the way the skill pins its oracle. The fake `todocli`
// replays those bytes by verb, so every cli-store test runs against the
// binary's own shapes; and, when a todocli binary is at hand
// (`TODOCLI_BIN`, or `todocli` on PATH), the same reads and writes are
// driven through it under a fully isolated environment, so the fixtures
// and the binary are checked against each other from this side too.
// Re-vendoring: copy the goldens over, then paste the pins this test
// prints on a mismatch.
import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { createHash } from "node:crypto";
import { spawnSync } from "node:child_process";
import { lib, here } from "./helpers.mjs";

const Store = lib("Store.js");
const Queue = lib("Queue.js");
const Errors = lib("Errors.js");
const Argv = lib("Argv.js");
const dir = path.join(here, "fixtures", "contract");
const fake = path.join(here, "fakebin", "todocli");

// sha256 of every vendored golden; todocli's tests/contract.rs regenerates
// them and fails when a sibling checkout's copy differs.
const PINS = {
  "board.json": "75ede613ca3e18ae05655977338be9f39bdc060af34e0457e75345634e0b2769",
  "envelope-auth.json": "df0146f24ce4d920f1a3553f1bf5c0c99be3b3a0cd09e78be9e4ec5ca5888373",
  "envelope-auth_unreachable.json": "c37cf36963da0cce37bdd78a18b66d391eddd20ecb2c5585bde0cf25f8e6dcb0",
  "envelope-busy.json": "2b817a4aed957e7e460762f5da85d4ca1ed25d1b85ba6a3b00184008665e6d45",
  "envelope-config.json": "043210cdb08627d90231f9dd87cd091f366746e962fcf92a2b7e5ce275c8118f",
  "envelope-db.json": "96cc984b92416f107f9d8df71ca9e94f2f01a1f42bc77a2e297b16e12ee96044",
  "envelope-error.json": "659a79cf76680513b3dad6c304510af5126f00206d922b76a2acbdfe354abee9",
  "envelope-list_gone.json": "35e6ff69863f525f50b07a367a36ad4223122cea7acd1703c288f2b6944a0aed",
  "envelope-not_found.json": "2d290b09b6d41b6d54eae5afc835516c804069af8b3b18f84a76d5bafc4ed2b8",
  "envelope-offline.json": "561e945616d7e736382e4b85ae6dacdd2d02b627dbf0a3a90cc8be00b1b02a77",
  "envelope-rate_limited.json": "fbcc42da81a2cdbb17b4fad6e1fc36738040ad37d753060dcd245be9302c576e",
  "envelope-refused.json": "304907699dc244578608ea5302ea721656ee88de12aa3d5cfc456b2c0c09bef8",
  "envelope-removals_held.json": "7855eba48adda0737a0161f6ed7f89f09eb7974b67a4d80184e04f02d9d685c1",
  "envelope-sync_held.json": "62831a6c0cc7ac3a579db5a6ed6f636863dd04131ad9c66353c7b373f7c84a99",
  "envelope-usage.json": "42970f6998b53b9ba01961259a1f093178a794c47f186e1bdc64fbb20598e9ce",
  "pomodoro-cancel.json": "b5d24c6483c975eac046dcdf9451c6358869109c4f2a7161dedda5ae4ff0ee3d",
  "pomodoro-done.json": "383a813b3989f6129109e7510fe73fc7503f8eb347fd6224e10d52cf7538a3a7",
  "pomodoro-interrupt.json": "b7dcfcbbf95a23ee59bdb561e26967181d9ffc9c2b715f728ff8130a5cea68db",
  "pomodoro-retarget.json": "26a560cea71bc863a2d2a0e56cb407a1924bde3a94ae7804d8e186aefa87ad99",
  "pomodoro-start.json": "a553305b029ad90ee0b1903e5b2bcd9d9e886f519032b0510a35772e1a7989c2",
  "sync-all.json": "c333d520c5d7c5c5570e8f47975d657026619a672664876d75cb07dae87c1f68",
  "write-add.json": "b040aa1f72f0818982eb5463f5fded4a4937ffad8aa5bfd1ac37deb6999b32e8",
  "write-done.json": "624a60cdf8eaf62ea84fb6dc6322b23bc4176ec5b77421bc6c533b6e1e26dad7",
  "write-focus-clear.json": "3368ea498e9490c52f7abc4589f078bdab156aa1c313e44706a2bbe4a005b39f",
  "write-focus-task.json": "2133d780e1b89c33588ad5e8299db29a9e32458e4927564ad0e801f77fcb3ab4",
  "write-reopen.json": "799b7b04d6ff8c3f62c7c7427c3ad454df9dbfa32506a76ad933a1b4d2de1a37",
  "write-rm.json": "a461205368529a353658c166f463194bbd3cc6bbc28d115bad03644e988c1e80",
  "write-start.json": "ccd6a9b759a57724135988e0e1733daba6aa909b8e14400dcee6fe26c48bc593",
  "write-step.json": "bb065a8dbb69a8a0ac5fe4c0004c57665e59784771cefa53694b2c4423bd951d",
};

const golden = (name) => fs.readFileSync(path.join(dir, name), "utf8");
const sha = (name) => createHash("sha256").update(fs.readFileSync(path.join(dir, name))).digest("hex");

function runArgv(argv, env, extra) {
  const r = spawnSync(argv[0], argv.slice(1), Object.assign({ env: Object.assign({}, process.env, env || {}), encoding: "utf8" }, extra || {}));
  return { code: r.status === null ? -1 : r.status, stdout: r.stdout || "", stderr: r.stderr || "", spawnFailed: !!r.error };
}

test("every vendored golden is pinned, every pin has its golden, and the bytes match", () => {
  const files = fs.readdirSync(dir).filter((f) => f.endsWith(".json")).sort();
  assert.deepEqual(files, Object.keys(PINS).sort(), "the vendored set and the pin table name the same files");
  const drift = files.filter((f) => sha(f) !== PINS[f]);
  assert.deepEqual(drift, [], "re-vendored goldens; new pins:\n" + files.map((f) => `  "${f}": "${sha(f)}",`).join("\n"));
  for (const f of files) assert.ok(JSON.parse(golden(f)), f + " is JSON");
});

test("the goldens are the shapes this panel parses: the board, every write reply, the sync reply, the envelope of every kind", () => {
  const board = Store.fromCli(golden("board.json"));
  assert.equal(board.ok, true);
  assert.deepEqual(board.items.map((t) => [t.id, t.name, t.status]), [["3", "Wire the webhook", "doing"], ["5", "Closed one", "done"]]);
  assert.deepEqual(board.focus, { text: "Ship the invoice-export slice", taskId: "3" });
  assert.deepEqual(board.sync.map((t) => t.name), ["obsidian"], "one target since todocli S10-1 (D18)");
  assert.equal(board.stamp, "$STATE_DIR/changed", "the stamp path, normalised by the generator");
  for (const verb of ["add", "start", "done", "reopen", "step", "rm"]) {
    const reply = JSON.parse(golden("write-" + verb + ".json"));
    assert.equal(typeof reply.id, "number", verb + " replies the affected task");
    assert.equal(Queue.rememberId({}, "tmp", golden("write-" + verb + ".json")).tmp, String(reply.id));
  }
  assert.equal(JSON.parse(golden("write-rm.json")).deleted, true);
  assert.deepEqual(JSON.parse(golden("write-focus-task.json")), { focus: "Ship the invoice-export slice", focus_task: 3 });
  assert.deepEqual(JSON.parse(golden("write-focus-clear.json")), { focus: null, focus_task: null }, "--clear clears the statement and the link (todocli 07988ed)");
  assert.equal(Queue.rememberId({}, "tmp", golden("write-focus-task.json")).tmp, undefined, "a focus reply names no task to map");
  const sync = JSON.parse(golden("sync-all.json"));
  assert.deepEqual(Object.keys(sync), ["targets"], "no basecamp object (D27)");
  assert.deepEqual(sync.targets.map((t) => t.name), ["obsidian"]);
  assert.deepEqual(Object.keys(sync.targets[0]), ["name", "enabled", "lastOkAt", "lastAttemptAt", "intervalSec", "error", "state", "hint", "notices"], "no counters (D27)");
  const kinds = fs.readdirSync(dir).filter((f) => f.startsWith("envelope-")).map((f) => f.slice("envelope-".length, -".json".length)).sort();
  assert.deepEqual(kinds, ["auth", "auth_unreachable", "busy", "config", "db", "error", "list_gone", "not_found", "offline", "rate_limited", "refused", "removals_held", "sync_held", "usage"], "the frozen kind vocabulary");
  for (const kind of kinds) {
    const env = JSON.parse(golden("envelope-" + kind + ".json"));
    assert.deepEqual(Object.keys(env), ["ok", "kind", "error", "code"], kind);
    assert.equal(env.kind, kind);
    assert.deepEqual(Errors.parseEnvelope(golden("envelope-" + kind + ".json")), { kind, message: env.error });
    const classified = Errors.classifySync(env.code, golden("envelope-" + kind + ".json"), "", false);
    assert.equal(classified.kind, kind, "classifySync names the envelope's kind");
    assert.equal(classified.store, undefined, "no sync failure is a store error");
  }
});

test("the fake replays the goldens by verb and prints the real envelope on FAKE_EXIT", () => {
  assert.equal(runArgv(Argv.forAction(fake, { type: "read" })).stdout, golden("board.json"));
  assert.equal(runArgv(Argv.forAction(fake, { type: "add", name: "x", description: "" })).stdout, golden("write-add.json"));
  assert.equal(runArgv(Argv.forAction(fake, { type: "setStatus", id: "3", status: "done" })).stdout, golden("write-done.json"));
  assert.equal(runArgv(Argv.forAction(fake, { type: "setStatus", id: "3", status: "doing" })).stdout, golden("write-start.json"));
  assert.equal(runArgv(Argv.forAction(fake, { type: "setStatus", id: "3", status: "todo" })).stdout, golden("write-reopen.json"));
  assert.equal(runArgv(Argv.forAction(fake, { type: "toggleStep", id: "3", n: 1 })).stdout, golden("write-step.json"));
  assert.equal(runArgv(Argv.forAction(fake, { type: "focus", id: "3" })).stdout, golden("write-focus-task.json"));
  assert.equal(runArgv(Argv.forAction(fake, { type: "focus", id: "clear" })).stdout, golden("write-focus-clear.json"));
  assert.equal(runArgv(Argv.forAction(fake, { type: "remove", id: "3" })).stdout, golden("write-rm.json"));
  assert.equal(runArgv(Argv.forAction(fake, { type: "syncNow" })).stdout, golden("sync-all.json"));
  const held = runArgv(Argv.forAction(fake, { type: "syncNow" }), { FAKE_EXIT: "75", FAKE_KIND: "sync_held" });
  assert.equal(held.code, 75);
  assert.equal(held.stdout, golden("envelope-sync_held.json"));
  const busy = runArgv(Argv.forAction(fake, { type: "read" }), { FAKE_EXIT: "75", FAKE_STDERR: "database is busy\n" });
  assert.equal(busy.stdout, golden("envelope-busy.json"), "75 without a kind is busy");
  assert.equal(busy.stderr, "database is busy\n");
  const replaced = runArgv(Argv.forAction(fake, { type: "read" }), { FAKE_EXIT: "1", FAKE_STDOUT: "" });
  assert.equal(replaced.stdout, "", "FAKE_STDOUT replaces the envelope");
  const unknown = runArgv([fake, "--json", "frob"]);
  assert.equal(unknown.code, 1);
  assert.match(unknown.stderr, /no contract reply/);
});

// The real binary, when one is at hand, under an environment that names
// every path todocli reads (HOME, XDG_*, TODOCLI_CONFIG, TODOCLI_DB): the
// live store, config, state directory and note are never touched. Skipped
// without a binary unless TODOCLI_REQUIRE_BIN is set (CI).
function todocliBin() {
  if (process.env.TODOCLI_BIN) return process.env.TODOCLI_BIN;
  for (const d of (process.env.PATH || "").split(path.delimiter)) {
    const p = path.join(d, "todocli");
    if (d && fs.existsSync(p)) return p;
  }
  return null;
}

test("the real todocli under an isolated environment prints the shapes the goldens hold", (t) => {
  const bin = todocliBin();
  if (!bin) {
    assert.equal(process.env.TODOCLI_REQUIRE_BIN, undefined, "TODOCLI_REQUIRE_BIN is set but no todocli is at hand");
    t.skip("no todocli binary (TODOCLI_BIN unset, none on PATH)");
    return;
  }
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "todo-contract-"));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const home = path.join(root, "home");
  fs.mkdirSync(home, { recursive: true, mode: 0o700 });
  const env = {
    HOME: home, XDG_CONFIG_HOME: path.join(root, "xdg", "config"), XDG_DATA_HOME: path.join(root, "xdg", "data"),
    XDG_STATE_HOME: path.join(root, "xdg", "state"), XDG_CACHE_HOME: path.join(root, "xdg", "cache"),
    TODOCLI_CONFIG: path.join(root, "config.toml"), TODOCLI_DB: path.join(root, "todo.sqlite3"),
    PATH: "/usr/bin:/bin", LANG: "C.UTF-8", TZ: "UTC"
  };
  const run = (action) => {
    const r = spawnSync(bin, Argv.forAction(bin, action).slice(1), { env, encoding: "utf8", cwd: home });
    return { code: r.status, stdout: r.stdout || "", stderr: r.stderr || "", spawnFailed: !!r.error };
  };
  const shape = (json) => Object.keys(JSON.parse(json));
  const add = run({ type: "add", name: "Buy milk --json", description: "Semi-skimmed" });
  assert.equal(add.code, 0, add.stderr);
  assert.deepEqual(shape(add.stdout), shape(golden("write-add.json")));
  const id = String(JSON.parse(add.stdout).id);
  assert.equal(Queue.rememberId({}, "tmp", add.stdout).tmp, id);
  for (const [action, name] of [
    [{ type: "setStatus", id, status: "doing" }, "write-start.json"],
    [{ type: "setStatus", id, status: "done" }, "write-done.json"],
    [{ type: "setStatus", id, status: "todo" }, "write-reopen.json"],
    [{ type: "focus", id: "clear" }, "write-focus-clear.json"],
    [{ type: "remove", id }, "write-rm.json"]
  ]) {
    const r = run(action);
    assert.equal(r.code, 0, name + ": " + r.stderr);
    assert.deepEqual(shape(r.stdout), shape(golden(name)), name);
  }
  const board = run({ type: "read" });
  assert.equal(board.code, 0, board.stderr);
  assert.deepEqual(shape(board.stdout), shape(golden("board.json")), "board --json keys: a todocli older than the goldens (no `stamp`) needs reinstalling from the crate, or name a build with TODOCLI_BIN");
  const doc = Store.fromCli(board.stdout);
  assert.equal(doc.ok, true);
  assert.deepEqual(doc.items, [], "the removed task is gone");
  assert.equal(Store.stampDir(doc.stamp), path.join(root, "xdg", "state", "todocli") + "/", "the stamp lives in the isolated state dir");
  assert.deepEqual(doc.sync.map((s) => s.name), ["obsidian"]);
  const sync = run({ type: "syncNow" });
  assert.equal(sync.code, 0, sync.stderr);
  assert.deepEqual(shape(sync.stdout), shape(golden("sync-all.json")));
  assert.equal(Errors.classifySync(sync.code, sync.stdout, sync.stderr, false), null);
  const missing = spawnSync(bin, ["--source", "omarchy", "--json", "show", "9"], { env, encoding: "utf8", cwd: home });
  assert.equal(missing.status, 1);
  assert.deepEqual(shape(missing.stdout), shape(golden("envelope-not_found.json")));
  assert.equal(missing.stdout, golden("envelope-not_found.json"), "the envelope carries no path, so its bytes are the golden's");
  assert.equal(Errors.parseEnvelope(missing.stdout).kind, "not_found");
  assert.ok(!fs.existsSync(path.join(os.homedir(), ".local", "state", "todocli", "contract-probe")), "nothing outside the sandbox");
});
